### ISSUE TITLE
Keepass Key Files?

### ISSUE THREAD

**Issue by reedspool** [roddhjav/pass-import#101]
Found one other person on the web asking the same question I have: https://unix.stackexchange.com/questions/567738/import-keepass-database-with-key-file-to-pass

Is there any way currently to import a keepass database (.kdbx) with a key file (.key)? Thanks!

**Comment by reedspool** [comment]
I solved this issue by opening it in my keepass client and re-saving without a keyfile. Feel free to close this, but maybe some comment on the readme could help a future newb like me? Anyways, thanks all for this amazing tool, that was super easy!

**Comment by roddhjav** [comment]
Hi, this feature is implemented and is present in the v3 branch. It is only a matter of time before it's being merged and released.

**Comment by reedspool** [comment]
Good to hear, I'll close this then, thanks!
