### ISSUE TITLE
Bitwarden - problem with notes and credit cards items

### ISSUE THREAD

**Issue by quentin-bettoum** [roddhjav/pass-import#107]
Hello,

I wanted to import my Bitwarden data, but I’ve had some problems. I’m new to Python but I tried my best to figure out what is happening.

Bitwarden allows to create different types of item, but they may not be in the CSV export file :
- Login (standard username with password, notes, custom fields, etc.) exported in CSV and JSON.
- Secure note (just a note with possible custom fields) exported in CSV and JSON.
- Card (credit card) exported in JSON only.
- Identity (personal information) exported in JSON only.

### Firstly, with the JSON format
When I tried to import my data as JSON with verbose it tells that it detects it as CSV and that the format _is not a valid exported Bitwarden file_.
The file is not accepted because of all the items that are not **login** type (cards, identities, and notes) and it then try to fall back to the default CSV format. If I remove them from the JSON, it works.
In this situation I'd expect the import not to break and warn the user of the items that cannot be imported.

### Secondly, with the CSV format
It works but it did not include the **totp field**.

I also noticed that the totp fields are not formatted (with both CSV and JSON) in the pass files and therefore not recognized by the pass-totp extension, but maybe it is a normal behaviour?

I made a pull request (#108) with the changes that allowed me to import my data and with updated Bitwarden samples for both JSON and CSV. 
But be aware that with these changes, the only way for me to import my notes and other types of item is to use the -a (--all) option. And then some data like **Credit Card** and **Identity** appears in Json in the pass file. But I can deal with that as the format that really mattered to me was the Notes.

However, it probably needs more work and it breaks a unit test (I am not capable of fixing it). You don’t have to keep all the changes but hopefully the updated samples will at least help a bit.

Thanks.

**Comment by roddhjav** [comment]
Hi, thank for the issue and the PR. I will investigate on this.
