### ISSUE TITLE
passwordstore.py/PasswordStore/list() cuts off first character of every path

### ISSUE THREAD

**Issue by harmtemolder** [roddhjav/pass-import#109]
The `+ 1` in `file = os.sep + str(ppath)[len(self.prefix) + 1:]`—line 84 of `passwordstore.py/PasswordStore/list()` ([link](https://github.com/roddhjav/pass-import/blob/bbf6afcfa34a23c3756bd157bc5b1c02fbef60af/pass_import/managers/passwordstore.py#L84))—results in the first character of every path being cut off. Could this be OS-specific (I run macOS Catalina) behavior of `os.path`? If not, and this happens for everybody, I'm happy to fix this into a pull request.

**Comment by roddhjav** [comment]
Thank a lot for the catch. This is indeed a bug. Fixed with 585b9c0.
