### ISSUE TITLE
Bitwarden - test samples don't contain custom fields, are they supported?

### ISSUE THREAD

**Issue by vivlim** [roddhjav/pass-import#110]
Bitwarden allows you to create arbitrary custom fields that are attached to items, does pass-import support those? I didn't see any examples in the bitwarden.json test asset.

I #107 when trying to import, so I wasn't able to actually see what happens when I import custom fields.

Here are a couple examples of what the resulting json & csv from bitwarden look like, for login items with every field (afaik) filled out + custom fields

```
    {
      "id": "c17a6a37-1868-4e07-973d-abee015b06c6",
      "organizationId": null,
      "folderId": "dcbda5be-7887-4205-a6e2-a7fe00753fd1",
      "type": 1,
      "name": "test-item",
      "notes": "Notes field allowing for freeform text input",
      "favorite": true,
      "fields": [
        {
          "name": "my text field",
          "value": "a value",
          "type": 0
        },
        {
          "name": "my hidden field",
          "value": "another value",
          "type": 1
        },
        {
          "name": "a boolean field which is off",
          "value": "false",
          "type": 2
        },
        {
          "name": "a boolean field which is on",
          "value": "true",
          "type": 2
        }
      ],
      "login": {
        "uris": [
          {
            "match": null,
            "uri": "https://test-uri-1"
          },
          {
            "match": null,
            "uri": "https://test-uri-2"
          }
        ],
        "username": "username",
        "password": "password",
        "totp": "1019"
      },
      "collectionIds": null
    },
```

```
Business,1,login,test-item,Notes field allowing for freeform text input,"my text field: a value
my hidden field: another value
a boolean field which is off: false
a boolean field which is on: true","https://test-uri-1,https://test-uri-2",username,password,1019
```
Each separate item in the CSV ends with a carriage return & newline, the custom fields are on their own lines *but do not end with carriage return*. I exported on Windows from the browser extension, haven't tested on other platforms to see if it behaves any differently.

**Comment by quentin-bettoum** [comment]
Hi,

I forgot to mention custom fields in my issue #107.

I managed to include custom fields when importing only with -a or --all option. Then they appear as JSON objects in the pass files.
For example : 

```bash
pass somePassFile

Passw0rd
login: Tom
fields: [{'name': 'some key', 'value': '123456', 'type': 1}, {'name': 'another field', 'value': 'abcdefg', 'type': 1}]
```

Thank you for the examples. I've included them in the updated CSV and JSON samples in my pull request.

> Each separate item in the CSV ends with a carriage return & newline, the custom fields are on their own lines but do not end with carriage return. I exported on Windows from the browser extension, haven't tested on other platforms to see if it behaves any differently.

It behaves identically on Linux with the Firefox extension, but I think I've tested the sample file which does not contain any CR and it worked, so I think it doesn't matter. But I may be wrong.
