### ISSUE TITLE
Source root path don't work on keepass 2.x KDBX

### ISSUE THREAD

**Issue by rlanore** [roddhjav/pass-import#112]
Hi,

I'm unable to import a partial kbdx file with -r or --root pimport options

```
 pimport pass keepassx2 my.kdbx --out ~/.password-store -k ~/.keeppass.key --root subfoler -p t
```
I have tried a lot of syntax

**Comment by roddhjav** [comment]
Hi, thank for this feedback. I simply forgot to implement the feature for keepass. This is now fixed with 1507fdc
