### ISSUE TITLE
io.UnsupportedOperation: not readable on generic csv imports

### ISSUE THREAD

**Issue by khoroo** [roddhjav/pass-import#113]
`pass import csv file.csv --cols 'title,login,password,group' -f -vvv`

gives
`  .  Trying to guess file format.
  .  Importer: csv, Format: csv, Version:
  .  Importing passwords from GenericCSV to PasswordStore
  .  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pass_import/__main__.py", line 329, in pass_import
    importer.parse()
  File "/usr/lib/python3/dist-packages/pass_import/managers/csv.py", line 38, in parse
    self.file.readline()
io.UnsupportedOperation: not readable

  w  not readable
 [x] Error: hm is not a valid exported csv file.`

without force - file already exists. looking through the code I suspect I'm either using the wrong syntax or its a bug to do with the file mode Python is opening `'w'`

**Comment by roddhjav** [comment]
This looks like #105. Can you try it using the master branch ?
