### ISSUE TITLE
Import OTP from 1Password

### ISSUE THREAD

**Issue by menteb** [roddhjav/pass-import#116]
When importing from 1Password using a `1pif` export file, the OTP field gets imported as:

`sections: [{'title': 'Related Items', 'name': 'linked items'}, {'fields': [{'k': 'concealed', 'n': 'TOTP_XXXXXXXXXXXXXXXXXXXXXXXXXXX', 'v': 'otpauth://totp/YYYYYYYYYYYYYYYYYYYYYYYYY', 't': 'One-Time Password'}], 'name': 'Section_ZZZZZZZZZZZZZZZZZZZ'}]`

This makes that [pass-otp](https://github.com/tadfisher/pass-otp) cannot find the OTP secret when querying. 
I reckon this is a pass-import issue as I'm sure there is a specific way of storing the OTP.

If there an easy fix I can apply?

**Comment by roddhjav** [comment]
Similar to #126, I will have a look a it once I get the time.

**Comment by b123400** [comment]
I've sent a PR for that https://github.com/roddhjav/pass-import/pull/157
