### ISSUE TITLE
andOTP to Keepass Export

### ISSUE THREAD

**Issue by ziaur25** [roddhjav/pass-import#117]
Can anyone show an example how to import any andOTP or aegis file and use this as library and export it to Keepass kdbx file? 
Thanks!

**Comment by roddhjav** [comment]
Run: `pimport keepass andotp path/to/andotp.json --out path/to/keepass.kdbx`

Add `-vvv` if you have any issue with it. I did not test the import of OTP credentials into keepass. So the data will be imported. However, I don't know if they will be directly usable by keepass otp extensions.
