### ISSUE TITLE
enpass2pass ignores duplicates

### ISSUE THREAD

**Issue by dhruvsinghal** [roddhjav/pass-import#12]
It appears that `enpass2pass.rb` ignores duplicates while importing from an `enpass`-generated CSV. This can potentially result in data-loss if someone imports a database, and then deletes the old database under the impression that everything was imported.

It would be great to (ideally) have this fixed, or for a warning to be placed in the `README` to that effect. Unfortunately, I'm not a Rubyist, or else I'd have made a pull-request for you.

**Comment by roddhjav** [comment]
Hi, thank for the feedback.
It's been a while but I want to let you know I'm aware of this issue and it will be fixed by the complete rewriting of `pass-import` that is almost ready. See #15

**Comment by roddhjav** [comment]
Should be fixed now.
