### ISSUE TITLE
Chrome import throwing SytnaxWarning

### ISSUE THREAD

**Issue by xerus2000** [roddhjav/pass-import#120]
```
❯ pass import chrome chrome-pwd.csv
/usr/lib/python3/dist-packages/magic/__init__.py:204: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if result is -1:
  w  
 [x] Error: chrome-pwd.csv is not a valid exported chrome file.

```

First line of the csv file:

	name,url,username,password,

**Comment by xerus2000** [comment]
Okay, it worked after exporting again, thanks :)

But the SyntaxWarning appeared anyways

**Comment by roddhjav** [comment]
After check, this is a new warning in the magic-file lib only visible from python 3.8+. It is not related to pass-import.
