### ISSUE TITLE
(NO BUG) assistance.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [roddhjav/pass-import#122]
Hello and thank you for this! 👍

I initially installed via pip, then after noticed "this installs pass-import but not the pass extension" so I then tried to build, I am using Android so changed the prefix to what I need but fails "(makefile:29 install) error 1, error: cannot copy tree 'build/scripts-3.8' not a directory" I notice "build" has no slash, is it because "DESTDIR" aka "/" is not prefixed here? anyway, main questions...

I understand that extensions are to placed in .../extensions directory, where is the extension file? and what is its name? that way I dont have to build it.
Perhaps, where it states "with pip the extension is not included", a hyperlink to the needed extension pointing us to its location would be very helpful!

Thank you again for this, really appreciated, cant wait to break free of corporate password managers and go open source!

**Comment by roddhjav** [comment]
Hi, The extension can be found under `scripts/import.bash`. It is a very simple bash script that is sourced by pass and that runs the `pass_import` python module. 

To be recognised as an extension by pass, this file needs to either be installed under `/usr/lib/password-store/extensions` or under `$PASSWORD_STORE_DIR/.extensions` (if you do this, you also to set PASSWORD_STORE_ENABLE_EXTENSIONS to 'true' for the extension to be enabled).

However, this file is not fully required if you use `pass_import` outside pass itself. Once you have the pass_import module installed (with pip), you also have the `pimport` script installed. Then, in a similar way to `pass import <manager> <file>`, you can run `pimport pass <manager> <file> --out password/store/dir`.

**Comment by 5c0tt-b0t** [comment]
My apologies for not closing this sooner! it worked perfectly importing my Aegis passwords via Termux on Android! I now use a bash script instead of a java app (Aegis) on my phone! its also requires a password or fingerprint to launch it! thank you!
