### ISSUE TITLE
Problem importing from pass to keepass

### ISSUE THREAD

**Issue by Th3Tr00p3r** [roddhjav/pass-import#124]
Hi,
I'm using a Linux subsystem (ubuntu terminal) from windows 10.
I'm attempting to create a keepass database (.kdbx) from my existing password-store (for backup purposes) using the command:
`pimport keepass ~/.password-store --out keepass.kdbx`
What happens is I immediately get this warning: `Unable to detect the pass format for /home/idomich/.password-store, using the default pass importer`, then there's a long pause (about 15 seconds), then I get the error: `Error: keepass.kdbx is not a password repository.`

So, what am I doing wrong here?
Regards,
Ido

P.S.
I have used pass-import successfully recently, to import the other way around (keepass --> pass)

**Comment by roddhjav** [comment]
Hi, pass-import do not create a database for you. You need to create your keepass database before and then run `pimport`.

**Comment by Th3Tr00p3r** [comment]
Thanks, I created an empty new database.dkbx and got it to work (another issue I had is that I created the database with windows, and I'm using import-pass from a linux subsystem...)

**Comment by Slowdive-Aideron** [comment]
@Th3Tr00p3r how did you do it the other way arround ? (keepass --> pass)
