### ISSUE TITLE
logins.csv fails to be imported from firefox

### ISSUE THREAD

**Issue by KarlWithK** [roddhjav/pass-import#128]
Perhaps I am doing this extremely wrong but I have done the following:
click 'Logins and Passwords' on firefox-> click 'export logins' -> run `pass import firefox logins.csv`.
However, I received the following error: ` [x] Error: logins.csv is not a valid exported firefox file.`
I checked the CSV file and I believe this was the correct file. Am I doing something wrong?

**Comment by roddhjav** [comment]
For firefox, you need to use the [ff-password-exporter](https://github.com/kspearrin/ff-password-exporter) tools to export your passwords. You can compare your csv format against [this file](https://github.com/roddhjav/pass-import/blob/master/tests/assets/db/firefox.csv) to ensure it is correctly supported.
