### ISSUE TITLE
firefox import

### ISSUE THREAD

**Issue by eoli3n** [roddhjav/pass-import#134]
#128 is not the right answer.
Firefox allows you to export your password from its tool directly.
Pass-import should use the native firefox format: 

```
"url","username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"
```

**Comment by eoli3n** [comment]
A workaround:
I had a strange second line which starts with ``"chrome://FirefoxAccounts"``
``FNR%2`` remove that second line, just remove that chain if it looks ok without.

```
awk -F',' 'FNR%2 {print $1","$2","$3}' logins.csv | sed 's/"url","username","password"/hostname,username,password/' > pass-logins.csv
pass import firefox pass-logins.csv
```

**Comment by roddhjav** [comment]
Fixed, see 9684777

**Comment by eoli3n** [comment]
Thanks

**Comment by pashtet04** [comment]
Will it get in 3.2 release?
