### ISSUE TITLE
Changes in pykeepass 4.0.0 breaks keepassxc import

### ISSUE THREAD

**Issue by dhedberg** [roddhjav/pass-import#136]
Trying to import a keepassxc database with pykeepass 4.0.0 results in 0 imported entries (no error is reported). Downgrading to pykeepass 3.2.1 fixes the problem.

The issue, at least the first one I encountered, seems to be that they now express paths as lists instead of strings.

**Comment by roddhjav** [comment]
Thank for reporting this. This is fixed with 86cfb1b
