### ISSUE TITLE
Extension script overrides PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by hennersz** [roddhjav/pass-import#139]
In the [extension script](https://github.com/roddhjav/pass-import/blob/master/scripts/import.bash#L21) it overrides PASSWORD_STORE_DIR to $PREFIX, which for me is an empty string. 

This causes importing using the command `pass import path/to/passwords.kdbx` to fail with the error `[x] Error:  is not a password repository.`  coming from [here](https://github.com/roddhjav/pass-import/blob/master/pass_import/managers/passwordstore.py#L250)  because prefix is an empty string.

If I unset PASSWORD_STORE_DIR and init the default password store `~/.password-store` it fails with the same error. 

Deleting line 21 from the bash script makes it work if PASSWORD_STORE_DIR is set, otherwise it fails with `KeyError: 'PASSWORD_STORE_DIR'`

This is on OSX 11.2.3, using pass version 1.7.3, bash 4.4, pass-import 3.1 and python 3.8

**Comment by roddhjav** [comment]
pass-import has been developed with the assumption that `PREFIX` is **not** empty. And it should not be empty as it is given by the [password-store source](https://git.zx2c4.com/password-store/tree/src/password-store.sh#n15) (unless you set `PASSWORD_STORE_DIR` to be empty yourself).

So there might be an issue somewhere in your pass install.

**Comment by hennersz** [comment]
ah you're right, I've found the issue,  I'm installing pass and this extension though nix, and the way the extension gets wrapped means prefix doesn't get passed from pass to the extension, 
https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/security/pass/extensions/import.nix#L37
I'll submit a fix

**Comment by hennersz** [comment]
fix added in NixOS/nixpkgs#118143
