### ISSUE TITLE
python-pykeepass new version

### ISSUE THREAD

**Issue by oscarpax** [roddhjav/pass-import#140]
pass-import doesn't import anything from `.kdbx` files, unless I add Python 3.9 to `setup.py`

**Comment by smadurange** [comment]
Ran into the same issue Now importing anything.

**Comment by roddhjav** [comment]
Could you provide more information on your error (with `-vvv`). What OS are you using? What pykeepass version?

**Comment by oscarpax** [comment]
Commit `e52623c` fixed the problem for me on Arch Linux with python-pykeepass 4.0.0-1. Thank you!
