### ISSUE TITLE
MacOs Big Sur - could not create '/usr/lib/password-store': Operation not permitted

### ISSUE THREAD

**Issue by meglio** [roddhjav/pass-import#142]
Dear community and the pass-import authors,

I tried to follow your installation guide on MacOS Big Sur. The very last command `sudo make install PREFIX=/usr/local` fails with the following error message:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/282177/114666841-e6762380-9d3d-11eb-8e78-bb35fc6b8910.png">

Your advice is appreciated. -- Thanks, Anton

**Comment by roddhjav** [comment]
Hi, this issue has been fixed on the master branch, can you use it instead. I just need to find the time to make a new release soon.

**Comment by meglio** [comment]
Thanks @roddhjav , will try building from the git repo. Should I still use `PREFIX=/usr/local` if I'm on BigSur?

**Comment by meglio** [comment]
Building from the git repo did help.
I suppose you'll only want to close this issue after making a new release, so leaving it open.
