### ISSUE TITLE
Import bitwarden export of an organisation

### ISSUE THREAD

**Issue by steinm** [roddhjav/pass-import#146]
Exported passwords of an organisation cannot be imported because the file is not recognized as a bitwarden export. Am I doing anything wrong?

**Comment by steinm** [comment]
Your example is a regular export of your own passwords. If you export the passwords of an organisation you get something like
`{
  "encrypted": false,
  "collections": [
    {
      "id": "658da523-a36f-43a6-8b1b-050199e2b401",
      "organizationId": "a00f9fe8-f72d-4445-9e5d-1be6b71b9074",
      "name": "Standardsammlung",
      "externalId": null
    },
  ],
....
  "items": [
    {
      "id": "56ccb3f4-ef80-44f2-baf3-7f2457beaad1",
      "organizationId": "a00f9fe8-f72d-4445-9e5d-1be6b71b9074",
      "folderId": null,`
    },
....
  ]
}

**Comment by roddhjav** [comment]
Ok, so I will have to also support bitwarden organisation export.

**Comment by steinm** [comment]
That would be great. It's actually very similar. The json file essentially has another section with collections. I'm not sure if they replace the folders or whether there could be a list of folders as well. The items at least have a folderId but when you add an item  to a organisation, you can't set the folder. Hence, collections are for grouping passwords in organisations just like folders are for grouping your own passwords.

**Comment by roddhjav** [comment]
Implemented with 3bdde2f.

**Comment by steinm** [comment]
Just build the debian package based on 3bdde2f and imported 250 passwords without problems. Thanks for taking care of this issue.
