### ISSUE TITLE
`sudo pip3 install pykeepass` - Failed to build pykeepass construct future

### ISSUE THREAD

**Issue by ccdd13** [roddhjav/pass-import#150]
Failed to build pykeepass construct future
but it say : Successfully installed ... pykeepass-4.0.1 ....

full log https://gist.github.com/ccdd13/b95789a99c6bf24469476625eccb756e

`uname -a` : `Linux mx1 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux`

**Comment by roddhjav** [comment]
This is pass-import, not pykeepass, please ask this on their own issue tracker.
