### ISSUE TITLE
Support for "--homedir" gpg option

### ISSUE THREAD

**Issue by EppurSiMu0ve** [roddhjav/pass-import#160]
```pass import``` doesn't work when trying to use it while gpg's ```GNUPGHOME``` is set to a different location from default one. For daily use I'm using in my ```.bashrc``` the ```GNUPGHOME=/home/user/.local/gnupg/``` and an alias ```alias gpg='gpg --homedir /home/user/.local/gnupg/'```

**Comment by roddhjav** [comment]
`GNUPGHOME` is supported and should work fine as it is essential for test. However alias are only interpreted by your shell, not by a running program, so you should ensure you use and export the `GNUPGHOME` environment variable.

See, in the test suite: https://github.com/roddhjav/pass-import/blob/master/tests/__init__.py#L144

**Comment by EppurSiMu0ve** [comment]
That's true. I've tested it again and it worked fine, I had may done something wrong previously. Thank you!
