### ISSUE TITLE
Error: invalid credentials, password encryption/decryption aborted.

### ISSUE THREAD

**Issue by ccdd13** [roddhjav/pass-import#162]
failed to import firefox passwords from exported csv file
<pre><font color="#FF5555"><b>❯</b></font> pass import -vv -a -c -C firefox logins.csv
<font color="#FF55FF"><b>  .  </b></font><font color="#AA00AA">Trying to guess file format.</font>
<font color="#FF55FF"><b>  .  </b></font><font color="#AA00AA">Importer: firefox, Format: csv, Version: </font>
<font color="#FF55FF"><b>  .  </b></font><font color="#AA00AA">Importing passwords from Firefox to PasswordStore</font>
<font color="#FF5555"><b> [x] </b></font><b>Error: </b>invalid credentials, password encryption/decryption aborted.
</pre>

**Comment by roddhjav** [comment]
See https://github.com/roddhjav/pass-import#gpg-keyring

**Comment by ccdd13** [comment]
my `.gpg-id` was configured with my full name which conflict with other gpg keys, setting it to a unique value line email or gpg hex key resolve my problem.

**Comment by generic-github-user** [comment]
For anyone coming across this in the future, I was able to solve this by reinitializing the password store with the same gpg-id and then running `pass import ...` (not entirely sure why this works).
