### ISSUE TITLE
Decoding - otp from keepassxc to pass

### ISSUE THREAD

**Issue by ghost** [roddhjav/pass-import#166]
Hi. 
Thank you very much for this tool, it saves a lot of work! 

I recently found out, that some characters of an otp I ported from keepassxc to pass, were decoded. 
In the original otp there were four = at the end of the token and each of it were decoded to %3D, wich is the HTML-Code for =. 
With oathool, wich is the tool [pass-otp](https://github.com/tadfisher/pass-otp) uses
`oathtool --base32 --totp secret_token`
Where secret_token is the one I copied from pass with the four %3D in it at the end,  I got the error: 
`oathtool: base32 decoding failed: Base32 string is invalid` 
After I checked the entry I saw that the problem was the decoding. 

I don't know if this is a problematic behaviour of pass-import, or (probably) just a problem caused by the website hoster that generate the otp token while ignoring conventions for that. 
Wikipedia says in base32 the = is used as a null-character.

When I use: 
`oathtool --base32 --totp secret_token` but replace each of the four %3D with the =, then it works.

**Comment by roddhjav** [comment]
Hi, Could you tell me a bit more on how you imported the otp. What it from a csv, xml, kdbx file?

**Comment by hacksenwerk** [comment]
Hey. 

I am sorry that was not a good report, I am still tired ^_^. 

Missing informations: 
`Debian 11 Stable Main `
```
Installed pass-import with the method described here: 
https://github.com/roddhjav/pass-import#installation- 
section: Debian/Ubuntu
```
Imported the keepassxc database by running this command: 
`pass import keepassxc database.kdbx`
```
Password for database.kdbx: 
 (*) Importing passwords from keepassxc to pass
  .  Passwords imported from: database.kdbx
  .  Passwords exported to: /home/Username/.password-store
  .  Number of password imported: 2
  .  Passwords imported:
	History/some:entry
	some_entry
```

**Comment by roddhjav** [comment]
Thank, I will do some test with kdbx file to see if they have special encoding for OTP. Just allow a few days.

**Comment by hacksenwerk** [comment]
@roddhjav Well thanks to you too and don't stress yourself about this, I've just edited the entry manually so it works again.
