### ISSUE TITLE
[Feature request] Support passff entries from firefox kdewallet integration imports for the kdewallet importer

### ISSUE THREAD

**Issue by ironhouzi** [roddhjav/pass-import#17]
Seems pretty dead after the major shift in FF: https://addons.mozilla.org/en-US/firefox/addon/kde5-wallet-password-integrati/?src=api ..

I am going to modify the kdewallet importer anyways, so I thought I might as well share the labour with others. The only thing that needs change is how the data is extracted, and how it's formatted into the pass entry.

If you want this feature, do you have suggestions for how to format multiple URL's for the same set of credentials?

**Comment by roddhjav** [comment]
I don't understand what you mean by this FR, passff is a browser extension and has nothing to do with import system.
