### ISSUE TITLE
gpg-key deprecated

### ISSUE THREAD

**Issue by santigz** [roddhjav/pass-import#176]
`README.md` indicates the use of `gpg-key` to install the project through APT and that makes `apt-get` show a deprecation warning at every update.
Please consider changing instructions it to something like this:
```
wget -qO - https://pkg.pujol.io/debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/pujol.io.gpg >/dev/null
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/pujol.io.gpg] https://pkg.pujol.io/debian/repo all main' | sudo tee /etc/apt/sources.list.d/pkg.pujol.io.list
```

**Comment by roddhjav** [comment]
Thank for the tip. I will update the doc.
