### ISSUE TITLE
Google Chrome import of passwords for hosts with a port number leads to filenames with ":" - not compatible with android and windows

### ISSUE THREAD

**Issue by petzsch** [roddhjav/pass-import#177]
Since I couldn't find anyone else complaining about this, here is my first and hopefully only issue of this awesome project :+1: 

After importing my passwordlist from Google Chrome's CSV format, I ended up with foldernames and filenames including the character ":" used for seperating the port numbers of the hosts I have been using.

Since I store my encrypted passwords on a nextcloud, I have the issue that I can't sync those passwords to my Windows box and my android phone.

I'm not sure if there is another character that could be used in the filenames/foldernames that browserpass and other plugins would treat as if it was a ":"

Any advice on this (admitetly) edge case, would be hightly appreciated.

**Comment by roddhjav** [comment]
Hey. You may want to try the `--convert` option as it will convert these invalid characters. If needed you can also configure what is converted using a configuration file. See https://github.com/roddhjav/pass-import#configuration-file

**Comment by petzsch** [comment]
hmm... allready started using the stored passwords and changing them quite a bit. (so no way to start over with another import)
Any chance to run the convert routine on an existing pass directory structure? (checked the man page of pass, there is no mentioning of --convert)

**Comment by roddhjav** [comment]
> Any chance to run the convert routine on an existing pass directory structure?

You can run it again with the `-f` option, it will overwrite the entry. Otherwise you can use the `--path` option to import (again) the passwords to a specific subfolder.

> (checked the man page of pass, there is no mentioning of --convert)

See: https://github.com/roddhjav/pass-import/blob/c021f1984a5a256092fb1dae3177247119d912f9/share/man/man1/pass-import.1#L67

**Comment by petzsch** [comment]
ok, got it sorted out... converted the passwords with -f and migrated the few passwords with port numbers into my prior backuped current store and removed all existing folders/files with ":".

Should have done that right on the first time. :-)

Thanks for the hint.
