### ISSUE TITLE
chrome2pass import issue

### ISSUE THREAD

**Issue by a-andreyev** [roddhjav/pass-import#18]
Hello! Exported chrome csv via [this guide](https://www.axllent.org/docs/view/export-chrome-passwords/), chrome google `62.0.3202.94`.
`pass import chrome chrome.csv`:
```
Traceback (most recent call last):
  File "/usr/lib/password-store/importers/chrome2pass.py", line 40, in <module>
    data = row['password'] + '\n'
KeyError: 'password'
```
So looks like `password` field changed to `password_value`, right?

**Comment by roddhjav** [comment]
Hi. This problem is known and has been fixed. Install the last version of pass-import from [here](https://github.com/roddhjav/pass-import/releases/tag/v2.0-beta) it should work fine.

**Comment by a-andreyev** [comment]
sorry, didn't noticed that! will mark archlinux pkgbuild as outdated :)
thank you!

**Comment by roddhjav** [comment]
Please don't mark it as outdated (I'm the maintainer of the arch package), this is a beta release, it's not ready to be deployed on arch repo.

**Comment by a-andreyev** [comment]
oh, got it! (excuse my ignorance :)

**Comment by roddhjav** [comment]
No problem at all.
