### ISSUE TITLE
aegis import encrypted json

### ISSUE THREAD

**Issue by janpeterd** [roddhjav/pass-import#187]
Hi, I encounter issues when importing an encrypted export from `Aegis` to pass with pass-import. I did install the cryptography python-module via pip.

command:
`pass import aegis /path/to/aegis-export.json`

output:

```
w  'str' object has no attribute 'get'
[x] Error: /path/to/aegis-export.json is not a valid exported aegis file.
```
However a non-encrypted export from aegis works fine.

**Comment by roddhjav** [comment]
Hi, Could you post the output with the `-vvv` option enabled. Also could you confirm your json file has the same format that this one: https://github.com/roddhjav/pass-import/blob/master/tests/assets/db/aegiscipher.json

**Comment by roddhjav** [comment]
Thanks for these information. It is indeed an issue in the format detection process.
The following will work: `pass import /path/to/aegis-export.json  -vvvf `, but not `pass import aegis /path/to/aegis-export.json  -vvvf`

I will fix it shortly.

**Comment by BenoitCartier** [comment]
That works perfectly, thanks!
