### ISSUE TITLE
Ship manpage with GitHub tarball? (match with PyPI)

### ISSUE THREAD

**Issue by sgn** [roddhjav/pass-import#192]
Hi, since you will upload tarball into PyPI anyway,
Could you please  also upload it into GitHub, or at least include man-pages in generated tarball?

That would save the trouble: time to build documentation, haskell is hard to be built on some platform.

**Comment by roddhjav** [comment]
Hi, I do agree, the new build deps add some issue. I will build the doc during the release process and remove this deps. This will go into the next release (hopefully soon).

**Comment by roddhjav** [comment]
Should be fixed with pass-import 3.4

**Comment by mcepl** [comment]
I don’t think this has been fixed:

```
 $ tar tvf pass-import-3.4.tar.gz |grep -w man
drwxrwxr-x root/root         0 2022-12-10 16:01 pass-import-3.4/share/man/
drwxrwxr-x root/root         0 2022-12-10 16:01 pass-import-3.4/share/man/man1/
-rw-rw-r-- root/root     19352 2022-12-10 16:01 pass-import-3.4/share/man/man1/pass-import.md
-rw-rw-r-- root/root     20586 2022-12-10 16:01 pass-import-3.4/share/man/man1/pimport.md
 $ 
```

**Comment by roddhjav** [comment]
You need to take the [signed asset](https://github.com/roddhjav/pass-import/releases/download/v3.4/pass-import-3.4.tar.gz), not the default github talbar.

**Comment by mcepl** [comment]
Right, that’s a PEBKAC. Sorry for bothering you.
