### ISSUE TITLE
Keepass2 CVS Import fails without username

### ISSUE THREAD

**Issue by realthargor** [roddhjav/pass-import#2]
It is possible to add an entry to Keepass(X)2 only containing a password and no username.
The import script fails on such entries when it tries to create a file ".gpg"

I did a quickfix, adding "(empty)" if username is not set, but i'm not sure if this is a valid solution.
The Usecase to have means/credentials with only a password is a valid one in my opinion.

**Comment by alexandrepujol** [comment]
Hi,

Yes, this is a valid use-case. I will work to fix this.
However, the import scripts are maintained by the upstream: https://git.zx2c4.com/password-store/tree/contrib/importers therefore this fix would have to be implemented in the upstream too.

**Comment by roddhjav** [comment]
It will be fixed by the complete rewriting of `pass-import` that is almost ready. See #15

**Comment by roddhjav** [comment]
Fixed now.
