### ISSUE TITLE
Show 'pass import' help info when doing 'pass --help' 

### ISSUE THREAD

**Issue by ikwyl6** [roddhjav/pass-import#205]
As a new user to pass and pass-import, I installed pass but didn't create a new db within pass as I'm just trying it out. I found ```pass import``` and I installed it. When messing around with the commands, I assume when I did a ```pass --help``` that I would have seen a ```pass import``` as one of the help options after installing it. Might not be feasible or easy to add but I would have assumed that since a plugin was installed that I would have seen ```import``` as one of the help options when doing ```pass --help```. 

If I put on my 'newbie user' hat, this probably wouldn't be intuitive to me to do ```pass import help```. I could be wrong.

**Comment by roddhjav** [comment]
This has been a feature request to pass for a long time. However, it has never been integrated, and this is not a thing that an extension can do (the extension simply does not have access to this). So, there is nothing I can do.

**Comment by ikwyl6** [comment]
Yeah ok. I kind of figured but I wasn't sure and also didn't check with ```pass```. thanks.
