### ISSUE TITLE
Confusing new user experience to import from Chrome (PyPI not up to date)

### ISSUE THREAD

**Issue by MadLittleMods** [roddhjav/pass-import#211]
The latest published version on [PyPI is `pass-import@3.4`](https://pypi.org/project/pass-import/#history) from 2022-12-10. But there have been [fixes for Chrome](https://github.com/roddhjav/pass-import/commit/363169271648e0b0f3ba77b29d2c3b55b2be76ad) since then which means it's impossible import from `chrome` -> `pass` when installing from PyPI.

### Reproduction instructions

Trying to use `pimport` to import from `chrome` to `pass` as indicated by the readme:

```sh
$ poetry init
$ poetry add pyaml
$ poetry add pass-import
$ poetry shell
# ❌ Doesn't work
$ pimport pass "/home/eric/Downloads/Chrome Passwords.csv" --out ~/.password-store
 [x] Error: Unable to detect the manager. Please try with: pimport <manager> /home/eric/Downloads/Chrome Passwords.csv

# ❌ Doesn't work
$ pimport pass chrome "/home/eric/Downloads/Chrome Passwords.csv" --out ~/.password-store
  w
 [x] Error: /home/eric/Downloads/Chrome Passwords.csv is not a valid exported chrome file.
```

Additionally, https://github.com/roddhjav/pass-import/issues/210 also complicates the problem if you're trying to use a path like `~/Downloads/Chrome Passwords.csv`. 

### Workaround

Build it from source:
```sh
$ git clone git@github.com:roddhjav/pass-import.git
$ cd pass-import
$ poetry init
$ poetry add pyaml
$ poetry add zxcvbn
$ poetry add requests
$ echo -e "\n\n[tool.poetry.scripts]\npimport = \"pass_import.__main__:main\"" >> pyproject.toml

$ poetry run pimport pass "/home/eric/Downloads/Chrome Passwords.csv" --out ~/.password-store --dry-run
[...]
Passwords exported: 1015
[...]
```

**Comment by roddhjav** [comment]
Yes... I need to make a new release and to polish a bit the packaging... I also need to find time for it. That should come soon...

**Comment by MadLittleMods** [comment]
No rush and sorry @roddhjav. I'm seeing how this is probably more of a bother now. Given the drive-by nature of needing to import once, I was trying to eliminate some of the immediate friction for future onlookers. And given one of of the issues being completely my fault, just adding some noise.

Feel free to close as people can still find and reference the info. Appreciate your responses!

**Comment by Sturmfahrt** [comment]
i am having a similar issue. for example when i use `$ pass import chrome passwords.csv` here is a screen shot with the output. 
![20240220_19h14m47s_grim](https://github.com/roddhjav/pass-import/assets/8572751/7b421179-3b67-4b3e-9eb3-88dfec6f3e9e)
i am able to replicate the issue by doing the same thing with `pimport' like how @MadLittleMods did.

**Comment by roddhjav** [comment]
All of this should be fixed now.
