### ISSUE TITLE
Import Nextcloud into QTPass?

### ISSUE THREAD

**Issue by coffseducation** [roddhjav/pass-import#221]
Is it possible to import Nextcloud passwords into QTPass running on Plasma 6?

I used both an export of .csv and .json but using

`pass import passwords.json
Error: import is not in the password store.`

qtpass version 1.4.0

Operating System: Garuda Linux 
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Dell Inc.
Product Name: Precision 5720 AIO

**Comment by roddhjav** [comment]
According to the error message, pass import is not installed correctly. Furthermore, QTpass is only a GUI for pass, therefore, there is nothing to import.

**Comment by coffseducation** [comment]
> According to the error message, pass import is not installed correctly. Furthermore, QTpass is only a GUI for pass, therefore, there is nothing to import.

Yes, apologies. I did not notice that the gpg key did not install with the AUR package.
I have now done so separately with: wget -qO - https://pujol.io/keys/0xc5469996f0df68ec.asc | gpg --import

QTpass is only a GUI - noted.

ps. I still cannot import Nextcloud passwords into Pass

`pass import /home/user/.password-store/Passwords+Folders+Tags_24_07_2024.json
(*) Importing passwords from 1password to pass
.  Passwords imported from: /home/user/.password-store/Passwords+Folders+Tags_24_07_2024.json
.  Passwords exported to: /home/user/.password-store
.  Number of password imported: 0
.  Passwords imported: 0
.  Passwords exported: 0`

**Comment by roddhjav** [comment]
Nextcloud is not supported yet, therefore it is normal it does not work.

**Comment by coffseducation** [comment]
Thanks.
