### ISSUE TITLE
slow `Popen.communicate`

### ISSUE THREAD

**Issue by ethey** [roddhjav/pass-import#225]
The import seems extremely slow using Python 3.12.6 on Linux. I have tested on two computers.
The instructions in `cli.py`
```python
            (stdout, stderr) = process.communicate(data)
            res = process.wait()
```
takes minutes to return (1h for 3 passwords…)

I tested a much simpler script [here](https://git.zx2c4.com/password-store/tree/contrib/importers/keepass2csv2pass.py) and I have observed the same phenomena.

I haven't had the time to test other version or platform.

Any idea why that may be?

**Comment by roddhjav** [comment]
That might be an issue on you side. I have just tested running the full test suite on python 3.12.6, with hundred of calls to `process`. It runs as expected, as fast as expected.

**Comment by ethey** [comment]
Thanks for taking the time to check. I will try something and close the issue if I am not able to solve this.

**Comment by ethey** [comment]
No clue what's happening with my Linux desktops. All seems fine on macOS with 3.12.6.

Thanks!
