### ISSUE TITLE
Python ModuleNotFoundError: No module named 'defusedxml'

### ISSUE THREAD

**Issue by N4M3Z** [roddhjav/pass-import#24]
After installing `pass-import` on OS X High Sierra 10.13.3 (17.4.0 Darwin Kernel Version 17.4.0) and running
`> pass import --help`
I am getting:
```
Traceback (most recent call last):
  File "/usr/local/lib/password-store/import/import.py", line 26, in <module>
    from defusedxml import ElementTree
ModuleNotFoundError: No module named 'defusedxml'
```

This can be of course fixed by simply running
```
pip install defusedxml
```

But it would imho be preferable to not have these sorts of dependencies.

**Comment by roddhjav** [comment]
Installation requirement (including defusexml) is already detailed in the readme file.

> But it would imho be preferable to not have these sorts of dependencies.

I don't know what you mean by "these sorts of dependencies". python-defusedxml is a XML bomb protection for Python stdlib modules. Therefore it offers a better xml parser than the default one. It is a fully legit dependency.

**Comment by N4M3Z** [comment]
I meant that it's good practice in Python to have a fallback to the default package if possible. Something like this:
```
try:
    import simplejson as json
except ImportError:
    import json
```
This is just a suggestion, feel free to close the issue.

**Comment by roddhjav** [comment]
I did it on purpose, the classic xml parser presents security issue. Therefore defusexml is not an optional dependency.
