### ISSUE TITLE
Chrome Import

### ISSUE THREAD

**Issue by vashalejandro** [roddhjav/pass-import#26]
Hi,
I've been trying to import my passwords from Chrome but so far I've been getting a FormatError.
Could you point me in the right direction to address this issue?

Thank you!
A

**Comment by roddhjav** [comment]
Hi,

Can you provide more information regarding your issue:
- Your chrome version,
- How did you export the passwords and in which format?

pass-import expects a csv file with the following header:
```
origin_url,username_value,password_value
```
If your csv file does not have the good header, you could change it to this one and it should work (assuming the rows are the same).

**Comment by vashalejandro** [comment]
Hi,

The Chrome version that I'm using is: 
```
Version 64.0.3282.140 (Official Build) (64-bit)
```

I exported the password in a csv file fallowing this [guide](https://www.axllent.org/docs/view/export-chrome-passwords/): 
  > Instructions
    In your Google Chrome (or Chromium, whichever you use), type the following in your URL bar: `chrome://flags/#password-import-export`, and then **enable** the feature.
    Restart your browser.
    Go to your passwords `chrome://settings/passwords` (you may have to wait a little while for your passwords to sync), then scroll down to below your passwords and you'll see two new buttons, `Import` & `Export`.
    Click `Export`, making sure you select the correct format (CSV).

My csv has the fallowing header:
```
name,url,username,password
```

I'll try changing to the header you pointed out:
>origin_url,username_value,password_value

Thank you!
A
