### ISSUE TITLE
Problems importing chrome passwords. 

### ISSUE THREAD

**Issue by maogouste** [roddhjav/pass-import#27]
Problems importing chrome passwords. 

Version : Version 66.0.3346.8 (Build officiel) dev (64 bits) Linux

I activated chrome://flags/#PasswordExport
I went to chrome://settings/passwords
clicked on the export menu line.
It created a Mots de passe Google Chrome.csv file
'cat file.csv | pass import chrome' was shouting : import.FormatError
I found https://github.com/roddhjav/pass-import/blob/master/tests/db/chrome.csv
compared with the Mots* file : The first column was extra, and the headers where different. 

As in :
name,url,username,password
 instead of 
origin_url,username_value,password_value

once corrected, everything went smoothly. 

Thanks for your great job.

**Comment by roddhjav** [comment]
Thank for this reporting. It confirms #26, I'll update the format asap.

**Comment by roddhjav** [comment]
Fixed with ea673ff
