### ISSUE TITLE
Too much cleaning

### ISSUE THREAD

**Issue by Sthing** [roddhjav/pass-import#31]
Hi Alex. 
In the PasswordManager method satanize you have this line:
```
self._clean_protocol(entry, 'url')
```
I do not think the URL should be cleaned like that.
I understand you use _clean_protocol() on the title because it is always used in a path name, and only for that.
But the url-property is primarily a piece of information, and we loose information if we just delete the protocol-prefix.

I propose that the _clean_protocol() method is retired and the funtionality moved to _create_path().

I would be happy to create a PR, but wanted to get your thoughts here first.

Best regards,
  Søren Thing

**Comment by roddhjav** [comment]
Hi Søren,
You are right, we protocol cleaning in `'url'` is not needed. As you proposed youreself, I am waiting for you PR. Just note, you cannot add this to `_create_path` because this function does not change the title.

**Comment by Sthing** [comment]
Fixed by https://github.com/roddhjav/pass-import/pull/33
