### ISSUE TITLE
Feature Request : Import from NetworkManager

### ISSUE THREAD

**Issue by emorrp1** [roddhjav/pass-import#38]
Please support importing the wifi keys from NetworkManager.

NM stores PSKs in plain text, so this is more of a useful backup mechanism for copying to new machines, rather than a password database importer.

You can get the SSID/PSKs wiith: `sudo grep -r '^psk=' /etc/NetworkManager/system-connections/ | awk -F'Auto |:psk=' '{print $2, $3}'` but I'm struggling to munge it to fit `pass insert` syntax wise.

**Comment by roddhjav** [comment]
I like this proposition, I will work on it asap.

**Comment by roddhjav** [comment]
Reopening, it still a work in progress.

**Comment by emorrp1** [comment]
Oops, yes just clicked the wrong button. Really impressed how quickly you got this working!
