### ISSUE TITLE
install fails on mac os sierra

### ISSUE THREAD

**Issue by academikuser** [roddhjav/pass-import#4]
➜  sudo make install
    Password:
    install: pass-import.1 -> /usr/share/man/man1/pass-import.1
    install: mkdir /usr/lib/password-store: Operation not permitted
    make: *** [install] Error 71

**Comment by roddhjav** [comment]
On MAC OS the prefix is `/usr/local` not `/usr`. (See [the homebrew doc](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#variables-for-directory-locations) for me information on this)

Therefore the only think you need to do is to change `PREFIX ?= /usr` by `PREFIX ?= /usr/local` in the `Makefile` and it should work.

**Comment by academikuser** [comment]
Thank you. I made the change to /usr/local in the MAKEFILE

Now I have a new error.

install: pass-import.1 -> /usr/local/share/man/man1/pass-import.1
install: mkdir /usr/local/lib/password-store/extensions
install: mkdir /usr/local/lib/password-store/importers
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64

**Comment by roddhjav** [comment]
It seems the `-D` option is not supported on MAC. Try without it.

**Comment by academikuser** [comment]
sudo make install
Password:
install: pass-import.1 -> /usr/local/share/man/man1/pass-import.1
install: illegal option -- t

ok, removed the 2 occurrences of -D and one of -t
I still get error 64.

**Comment by N4M3Z** [comment]
As far as I can tell, `install` on OS X simply does not support the use case in this Makefile:
```
@install -Dm0755 -t "$(DESTDIR)$(IMPORTERS_DIR)/" importers/*
```
Since the `-D` and `-t` options are not available and there is no other way to use install on source and destination directory:
```
install [-bCcMpSsv] [-B suffix] [-f flags] [-g group] [-m mode] [-o owner] file1 file2
install [-bCcMpSsv] [-B suffix] [-f flags] [-g group] [-m mode] [-o owner] file1 ... fileN directory
install -d [-v] [-g group] [-m mode] [-o owner] directory ...
```
So the line has to be replaced with something like this:
```
@cp -r importers/* "$(DESTDIR)$(IMPORTERS_DIR)/"
@chmod 755 "$(DESTDIR)$(IMPORTERS_DIR)/*"
```

**Comment by N4M3Z** [comment]
Unfortunately, once you get there, there are other issues. The native bash version on OS X is ancient:
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
```
and does not support `typeset -A` command, one has to install newer one. Then, if you are using Homebrew, the plugin does work since it defaults to
```
IMPORTER_DIR="${PASSWORD_STORE_IMPORTER_DIR:-/usr/lib/password-store/importers}"
```
instead of `/usr/local` for Homebrew support on OS X, but really this should just use the PREFIX.

**Comment by roddhjav** [comment]
Thank a lot for this help. I don't have a OS X system myself and therefore I cannot test it. It seems you fixed this issue, therefore, could you work on a pull request on this?

**Comment by N4M3Z** [comment]
Hi, I tried to minimize the amount of work so that I could get it running, the steps above are just a way to quick fix this. Some amount of work needs to be done, to make the changes compatible across platforms. Changing the Makefile is pretty straightforward, I can make a PR for that, but the problem with the `typeset` and the default path requires some work.

**Comment by roddhjav** [comment]
It will be fixed by the complete rewriting of `pass-import` that is almost ready. See #15

**Comment by roddhjav** [comment]
Should be fixed now.
