### ISSUE TITLE
Error when import from firefox (passwordexporter)

### ISSUE THREAD

**Issue by BrunIF** [roddhjav/pass-import#40]
```bash
pass import passwordexporter ff.csv
Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 758, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 714, in main
    importer.parse(file)
  File "/usr/lib/password-store/import/import.py", line 586, in parse
    self._checkline(file)
  File "/usr/lib/password-store/import/import.py", line 272, in _checkline
    raise FormatError()
import.FormatError
```

File format:
```csv
hostname,username,password
https://wordpress.com,login,******
https://www.ratatype.com,mail@mail.com,*******
````

**Comment by roddhjav** [comment]
Hi,

Could you provide more information on your issue:
- Which version of firefox
- Which version of passwordexporter

**Comment by BrunIF** [comment]
Firefox 60
FF-Password-Exporter-1.0.0-x86_64.AppImage

**Comment by roddhjav** [comment]
Ok, It explains why it does not work, the importer supported by the `passwordexporter` command is the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/password-exporter/) (that does not support Firefox 57+). I did not know there is a new native application for it. I will have a look at it and update the command `passwordexporter` for this app.

**Comment by roddhjav** [comment]
It should be fixed now. Thank for reporting this.

**Comment by BrunIF** [comment]
Work!
