### ISSUE TITLE
Chrome Import Issue

### ISSUE THREAD

**Issue by steveharriss** [roddhjav/pass-import#42]
Using 2.2 on Linux. FF import fine. Exports form Chrome/Chromium fail to import with errors:

Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 753, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 709, in main
    importer.parse(file)
  File "/usr/lib/password-store/import/import.py", line 282, in parse
    self._checkformat(reader.fieldnames)
  File "/usr/lib/password-store/import/import.py", line 277, in _checkformat
    raise FormatError()
import.FormatError

Chrome Version 49.0.2623.75 (64-bit)
Chromium Version 66.0.3359.181 (64-bit)

Unable to directly export from browsers so used the hack using sqlite3
sqlite3 -header -csv -separator "," ~/.config/chromium/Default/Login\ Data "SELECT * FROM logins" > ~/ChromiumPasswords.csv

Any ideas how I can circumvent this?

**Comment by roddhjav** [comment]
Could you provide the header of your csv file?

**Comment by steveharriss** [comment]
Morning, here is the default sqlite3 export header:
origin_url,action_url,username_element,username_value,password_element,password_value,submit_element,signon_realm,preferred,date_created,blacklisted_by_user,scheme,password_type,times_used,form_data,date_synced,display_name,icon_url,federation_url,skip_zero_click,generation_upload_status,possible_username_pairs

**Comment by roddhjav** [comment]
So it seems the CSV format provided by sqlite3 is quite different from the standard one (see the test database in https://github.com/roddhjav/pass-import/blob/master/tests/db/chrome.csv). I will investigate on this sqlite3 format and probably add a specific support for it. However I won't have the time to work on it before a few weeks.

**Comment by steveharriss** [comment]
No problem. I got them into pass using keepassxc to import and your already built import from that program. It should be useful to others though going forward. Keep up the good work
