### ISSUE TITLE
another chrome import issue

### ISSUE THREAD

**Issue by whitered** [roddhjav/pass-import#43]
I had 4 passwords for 192.168.1.1 in chrome,
after importing to pass all data preserved correct except for filenames:
```
 .  Passwords imported:                                                                             
       chrome/192.168.1.1                                                                             
       chrome/292.268.2.2                                                                             
       chrome/393.368.3.3                                                                             
       chrome/494.468.4.4
```

**Comment by roddhjav** [comment]
Hi, Thank for this bug report. It is mostly due because as for now, the duplicate path system is very simple. It is planned to change it in the close future (see #41). However I won't have the time to work on it before a few weeks.

**Comment by roddhjav** [comment]
This should now be fixed.
