### ISSUE TITLE
1Password and Unicode characters

### ISSUE THREAD

**Issue by HiPhish** [roddhjav/pass-import#46]
Hi,

I have been trying to import my 1Password data and this script kept choking on characters outside the ASCII range. This is a big problem, because 1Password uses the checkmark character (`0xE2 0x9C 0x93`) *a lot*. I had to pipe the output of GPG through sed first before pass-import would finish correctly.

**Comment by roddhjav** [comment]
Hi,

Could you provide more information on your issue, like:
1. The version of 1password you used,
2. The command and exporter you use (`1password`, `1password4`, `1password4pif`)
3. An example of data that cause the issue

**Comment by HiPhish** [comment]
I use 1Password 6.8.9 on Mac, I exported a `.pif` file and I used `1password4pif`. I cannot test it out right now, but here is a dummy PIF that contains a character outside the ASCII range (`ü`):
```
{
  "uuid":"A8F542CF2A4E4F35BBB15D455630AA67",
  "updatedAt":1531778882,
  "securityLevel":"SL5",
  "contentsHash":"ea6f0f52",
  "title":"Nonsense",
  "secureContents":
    {
      "notesPlain":"This contains ünicode.",
      "fields":
        [
          {
            "value":"herp",
            "name":"username",
            "type":"T","designation":"username"
          },
          {
            "value":"herp",
            "name":"password",
            "type":"P",
            "designation":
            "password"
          }
        ]
    },
  "txTimestamp":1531778929,
  "createdAt":1531778882,
  "typeName":"webforms.WebForm"
}
***5642bee8-a5ff-11dc-8314-0800200c9a66***
```
I have reformatted it for better readability. Oh and BTW, I was using the git version of pass-import, not the stable release.

**Comment by roddhjav** [comment]
That's weird because pass-import open 1pif file in a utf8 encoding format, so it should work fine.

**Comment by HiPhish** [comment]
It might have had something to do with my locale, yesterday PlayOnLinux wasn't working either with the same error message until I switched my locale back to the default C locale (in the KDE settings). I think this is the root cause and the issue can be closed.
