### ISSUE TITLE
Total number of imported passwords is wrong. 

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#54]
When i try to import a keepass 2.38 xml then i get alot of warnings:

```
  w  Impossible to insert NewDatabase/amazon.com (someone@company.com) into the store: gpg: [stdin]: encryption failed: Invalid user ID
Password encryption aborted.
 CW: verify_file()
GPG:
gpg2
GPG Options:

Param 1
/home/christian/.password-store/.gpg-id
Enter contents of NewDatabase/amazon.com (someone@company.com) and press Ctrl+D when finished:
```
These warnings are ok.

This leads "pass import" not not import the password, just creating the directory structure. Which is ok from my point of view. 

But the summary is plain wrong:
```
 (*) Importing passwords from keepass
  .  File: /home/christian/zusammengefasst.xml
  .  Number of password imported: 1248
  .  Passwords imported:
[...]
```
there was not a single password imported, so "Number of password imported" should be 0 instead of 1248.

You can find my pass version, pass-import version etc. in https://github.com/roddhjav/pass-import/issues/52

**Comment by christian-weiss** [comment]
Background:
I try to do some tests to check the robustness of pass-import, and if i can recommend it to others.
I put some GPG fingerprints to .gpg-id file which are not in my gpg keyring, so the error is expected, but summary is misleading.

**Comment by roddhjav** [comment]
Hi again @christian-weiss thank for this finding. I will fix this asap. I think for this kind of error pass import should fail and not print any success message at all.

> I try to do some tests to check the robustness of pass-import, and if i can recommend it to others.

That's great. You can see in the test suite, pass-import is already quite robust. But that's right the test do not (yet) cover all the cases. You are more than welcome to provide as many comments, bugs and implementation issues you can found. I will be more than happy to fix them.

**Comment by roddhjav** [comment]
This is fixed with 67f62ecf0f372251df9a900211841540769bbcba

*Note:* this is a fast and **temporary** fix. A better fix will come later as part of much bigger change in pass-import. See #53

**Comment by christian-weiss** [comment]
As this issue is no big deal for me, i can wait, i guess you have all details required to reproduce that issue.

**Comment by roddhjav** [comment]
I just fixed it properly this time. However, its in #53
