### ISSUE TITLE
pass import --clean is missleading

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#56]
Description of "-c" and " --clean" command line option is "Clean data before import.".

I thought this will clean-up my password store (~/.password-store/) and removes everything except:
~/.password-store/.git
~/.password-store/.gpg-id

I learned by issue https://github.com/roddhjav/pass-import/issues/55 that this is not the meaning for that option. 

I recommend to (long-term) remove  "-c" and "--clean" (depricated it in next release) and to add new option:

```
--replace-path-separators 
# (default "/"-->"-" and "\"-->"-")
```

```
--replace-path-separators="_" 
# ( "_" or any other allowed character)
```
```
--replace-path-separators="" 
# (to delete it; replace it with nothing)
```

As i am working in teams and git repo is team-shared (using .gpg-id for access management), i recommend to add a .pass-import file to the root to share pass-import config settings with the team. Pass-import should pick it from .pass-import first and should allow overriding via command line options.
Config file should contain a setting if this option should be active and with charater so use.

**Comment by roddhjav** [comment]
It's an interesting proposal, I am going to implement it

**Comment by roddhjav** [comment]
I added a config file its a ini file that works as follow:

```sh
$ cat ./password-store/<root>/.import
[convert]
separator = -
```

If you have better ideas regarding this file (including its format) you are welcome to propose.

The separator can also be set by the `--separator` option.

**Comment by christian-weiss** [comment]
good.

Would be cool if you can add invalids and cleans, too:
```
$ cat ./password-store/<root>/.import
[convert]
separator = -
cleans = " ": "_", "&": "and", "@": "At", "'": "", "[": "", "]": ""
invalids = '<', '>', ':', '"', '/', '\\', '|', '?', '*', '\0'
```
or similar
