### ISSUE TITLE
Import with --clean failed

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#57]
Command line statement:
`pass import --clean --extra keepass zusammengefasst3.xml`

Error
```
Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 778, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 733, in main
    importer.satanize(arg.clean)
  File "/usr/lib/password-store/import/import.py", line 271, in satanize
    entry['title'] = self._clean_cmdline(entry['title'])
KeyError: 'title'
```

On Ubuntu with most up-to-date git version.

By the way: Dealing with data is sometimes like fighting with the devil (satan), but please still try to do "sanity checks" instead of "satanizing" data. ;-) (see python function "satanize")

**Comment by roddhjav** [comment]
Historically I had the assumption a password title cannot be empty. In the scope of `pass`, its make sense. This is now fixed.
