### ISSUE TITLE
Not showing custom site port number

### ISSUE THREAD

**Issue by BrunIF** [roddhjav/pass-import#59]
<img width="725" alt="brun devops-pro 10 10 10 1 - byobu tmux 2018-11-27 10-42-52" src="https://user-images.githubusercontent.com/490917/49069307-a3c95480-f231-11e8-87af-8999c9e83e25.png">
When I type hostname `10.10.0.1` and pressing `tab` key then autocompleate not show me port.

May be port need write after dash `-`?

**Comment by roddhjav** [comment]
Hey, maybe you should try with `pass 10.10.0.1:` ?

**Comment by BrunIF** [comment]
Probably this bug needs to be created in the password-store. Their auto-completion is not working properly. All passwords are recorded in the database.
<img width="208" alt="image" src="https://user-images.githubusercontent.com/490917/49213133-3d2c6e00-f3cc-11e8-8cfa-59993a24a4fc.png">
