### ISSUE TITLE
Feature Request : Import from Dashlane

### ISSUE THREAD

**Issue by mandarvaze** [roddhjav/pass-import#6]
Please support importing the data from Dashlane

I was able to do that, using Dashlane's Unsecure CSV format, but I had to "shift" some columns, and used ``keepass2csv2pass.py``

**Comment by roddhjav** [comment]
A Dashlane importer is on my todo list, but not now. Moreover, Dashline doesn't work on Linux therefore it will be hard to generate a Dashline export.

If the importer you did works, fell free to submit it in a pull requests.

**Comment by roddhjav** [comment]
Dashlane will be supported in `pass-import 2.0`. See #15

**Comment by roddhjav** [comment]
pass-import now supports import from dashlane.
