### ISSUE TITLE
Does it import with spaces?

### ISSUE THREAD

**Issue by BarbzYHOOL** [roddhjav/pass-import#60]
I used the old 2012 import script from keepassx to pass but it screwed up all the directories and password names, they don't have any empty space.

I would like to try pass-import but I can't install it easily on the old ubuntu 14.04 :'(

**Comment by roddhjav** [comment]
Hi, sorry for the delay.
Yes, it does support the import of entry with spaces in the names.

**Comment by BarbzYHOOL** [comment]
thank you!
