### ISSUE TITLE
Import binary attachment

### ISSUE THREAD

**Issue by zioalex** [roddhjav/pass-import#63]
Hi,
I am trying to convert a keepass file in pass. 
I exported the file in xml with the expectation that the binary attachment would be there but no way.

I do not see it. Is pass-import in any case capable to import them. I do not see any option for it.
Cheers

**Comment by roddhjav** [comment]
Hi, `pass-import` currently does not support the import of binary attachment. However, this could be a nice feature to add.

It is a nice proposal because `pass` support binary file. However, I don't know if a lot of other password manager do support binary files. Like it does not seems keepass support them.

**Comment by zioalex** [comment]
Actually Keepass support binary attachment. The problem was that the XML export didn't contain them.
However with pschmitt/pykeepass/issues/109 I'd been able to extract the attachment. Now which is the best way to proceed to import them?

**Comment by roddhjav** [comment]
ACK, after check keep indeed, support binary files.

[pschmitt/pykeepass](https://github.com/pschmitt/pykeepass) seems nice, I will most likely use it in pass-import to support binary file import once the feature will be implemented.

As a temporary solution, supposing you ran the code you provided in https://github.com/pschmitt/pykeepass/issues/109#issuecomment-449024682, it means you have all the files in a tmp directory. So you can import them to pass with something like:
```sh
for file in tmp/*; do
    pass insert -m tests/$file < $file
done
```

**Comment by zioalex** [comment]
If possible I would try to import pykeepass and add a function in pass-import to have them in the correct place.

**Comment by zioalex** [comment]
I am trying to understand your code to find out the place where to catch the Binary Element.
I think it should be in the Keepass(KeepassX) class but still not clear how to do it.

**Comment by roddhjav** [comment]
Ok, then will soon create a branch with this early feature. 

You would need to put override the parse function which is the main function called for very manager and that read the import file.
```python
class Keepass(KeepassX):

    ...

    def parse(self, file):
        super(Keepass, self).parse(file)
        # your code here
```

**Comment by zioalex** [comment]
Created pull request https://github.com/roddhjav/pass-import/pull/68
