### ISSUE TITLE
Dir with trailing space: dir creation failed on windows (git clone)

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#64]
Import of following snippet from a keypass2 xml file:
```
<Group>
...
<Name>Tinmachine / Nutrition</Name>
...
</Group>
```
resulted in 2 dirs on my ubuntu disk:
`Tinmachine ` (incl. trailing space)
and
` Nutrition` (incl. leading space; not visable in github markup)

When cloning this repo on a windows machine this results in dir named `Tinmachine` (without trailing space) and a failure when trying to create a dir in it named `  Nutrition` (with leading space; not visable in github markup), but it fails, as it can not navigate to a dir name `Tinmachine ` (with trailing space).

**Comment by christian-weiss** [comment]
shell on ubuntu
```
ls -al
drwx------ 3 christian christian 4096 Dez 21 16:07 'Tinmachine '/
cd Tinmachine\ /
Tinmachine $ cd \ Nutrition/
```


this was discovered while testing your change from:
https://github.com/roddhjav/pass-import/issues/55
https://github.com/roddhjav/pass-import/issues/56

**Comment by roddhjav** [comment]
Can you confirm me you use the convert option when importing this?

**Comment by christian-weiss** [comment]
Please re-open this issue due to:
https://github.com/roddhjav/pass-import/issues/97

Statement is:
`pass import --convert --all keepass zusammengefasst.xml`

Error:
```
fatal: cannot create directory at '/my/path/Tinmachine / Nutrition': no such file or directory
```

My password-store contains the file `.import`:
```
# Separator string
separator: '-'

# The list of string that should be replaced by other string. Only activated
# if the `clean` option is enabled.
cleans:
  ' ': '-'
  '&': 'and'
  '@': At
  "'": ''
  '[': ''
  ']': ''

# The list of protocol. To be removed from the title.
protocols:
  - http://
  - https://

# The list of invalid caracters. Replaced by the separator.
invalids:
  - '<'
  - '>'
  - ':'
  - '"'
  - '/'
  - '\\'
  - '|'
  - '?'
  - '*'
  - '\0'
```
(i know these are the defaults, but i expect that defaults may vary in future releases and releases may vary on some of our team mates PCs - repo is team-shared.

The `/` (forward slash) is not a `path separator` on Win10, but it is still not allowed in directory names on windows (NTFS). Forward slash should be replace by `separator` (in this case: `-`) by `--convert`.

Ubuntu system:
Ubuntu 19.10
pass 1.7.3
pass import 2.6
keypass xml from keepass 2.38
git version 2.20.1

Windows system:
Windows 10 64-bit
git bash (Git for Windows): GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)

**Comment by roddhjav** [comment]
cf #65
