### ISSUE TITLE
Filename generated on ubuntu and commited can not be created on windows (git clone)

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#65]
Import of following snippet from a keypass2 xml file:
```
<Group>
...
<Entry>
<String>
<Key>Title</Key>
<Value>MySQL  	web400_db2 </Value>
</String>
</Entry>
...
</Group>
```
Hex representation of Value:
```
4D 79 53 51 4C 20 20 09 77 65 62 32 30 30 5F 64 62 32 20
```

results in following file:
```
ls -al
-rw------- 1 christian christian  521 Dez 21 16:07 'MySQL__'$'\t''web400_db2_.gpg'
```
this part of the filename results in file creation problems on windows:
```
'$'\t''
```

**Comment by christian-weiss** [comment]
this was discovered while testing your change from:
#55
#56

**Comment by roddhjav** [comment]
Hi, this is because pass-import only import the attached file name, not the actual binary content. As you can see in https://github.com/roddhjav/pass-import/pull/68, this is being developed.

**Comment by christian-weiss** [comment]
Please re-open this issue due to:
https://github.com/roddhjav/pass-import/issues/97

Statement is (on Ubuntu):
`pass import --convert --all keepass zusammengefasst.xml`

Followed by (on windows):
`git clone http://gitlab.fritz.box/myname/passwordstore-bugtester` 

git prints this error:
```
error: unable to create file /my/path/MySQL     web200_db2.gpg: invalid argument
```

Ubuntu system:
Ubuntu 19.10
pass 1.7.3
pass import 2.6
keypass xml from keepass 2.38
git version 2.20.1

Windows system:
Windows 10 64-bit
git bash (Git for Windows): GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)

**Comment by roddhjav** [comment]
You need to use both the `--clean` and the `--convert` options for this.

**Comment by christian-weiss** [comment]
```
pass import --help
...
  -c, --clean           Make the paths more command line friendly.
  -C, --convert         Convert invalid caracters present in the paths.
...
```

Expectation:
As above filename is invalid, i expect that the issue is solved by `--convert`. The option `--clean` is just to make the filename more convenient when working with the command line. 

Please move or copy this specific behaviour to `--convert`.

BTW: There is a typo: "caracters" should be "characters". I saw this typo on many places in the code and documentation incl. github release notes.

**Comment by roddhjav** [comment]
You are right, the option name are not really good. I will definitely rewrite this.
In practice, the only difference between the two command is that the convert option replace characters by the separator while the clean replace the characters by other.

**Comment by christian-weiss** [comment]
@roddhjav  would be cool if you can re-open this ticket, as long as it is not implemented / resolved.
