### ISSUE TITLE
Keepass string fields 

### ISSUE THREAD

**Issue by wahlis** [roddhjav/pass-import#66]
I have OTP-keys stored in Keepass. They are stored as string field with the name otp and the value key=xxxx They do not get imported even with the -e extra option

**Comment by jason076** [comment]
It seems that the -e option has no effect at all, while importing a keypass xml file.

**Comment by roddhjav** [comment]
This is now fixed. Sorry for the delay to fix this. The issue was more general, the extra option was useless for all XML based importer.

**Comment by sevillaarvin** [comment]
In case someone finds this, --extra was renamed to --all:

8f19ea4957647808a398030cc8ddbb2ff24d8ab7

to use:

`pass import -a keepass file.xml`
