### ISSUE TITLE
Allow for local installation

### ISSUE THREAD

**Issue by stefanct** [roddhjav/pass-import#70]
Currently the makefile is only suited for system-wide installation which requires administrator access. Since imports are probably only done once it might be very nice to not clobber the system directories or even having to ask an administrator to install it.

`pass` itself allows installing extensions into the `.password-store` directory in an `.extensions` subdirectory. `pass-import`'s use of Python complicates things a bit, but it could be implemented by providing a suitable makefile recipe to install the scripts (`python3 setup.py install --root=~/.password-store/.extensions` + `ln -s ... import.bash` somewhat worked for me ;) plus something like `export PYTHONPATH=$PASSWORD_STORE_DIR/.extensions/usr/local/lib/python3.5/dist-packages/` in `import.bash`.

**Comment by roddhjav** [comment]
Hi, this is a nice proposal. I implemented it with 5d32355b66f776e8bf664e8ce4ef87d4cbecce9c

Note that because it is a local installation, there is no manual page or shell completion.

**Comment by stefanct** [comment]
Hm... `man` supports paths as parameter to open a man page file, so in theory one could just add `pass-import.1` to the local install directory. Likewise instead of the warning one could instruct the user to add the required `source` command(?) to her `.bashrc` or even ask if it shall be appended automatically. Both is probably kinda overkill though and in my opinion this issue can be closed. Thanks!
