### ISSUE TITLE
Import from LastPass mangles (shared?) folders with only one password in them

### ISSUE THREAD

**Issue by cincodenada** [roddhjav/pass-import#8]
This is mostly a reminder to myself to investigate further here, so don't spend to much energy on it yourself yet, I hope to put in a PR.

But I believe this what is happening; I just used this to import my LastPass export, and there was an `_etc"` folder with a few files that had the name of a former folder (e.g. `"myemail\Web_Hosting.gpg`). Those folders had one entry in them.

These should be instead be files in `myemail\Web_Hosting`, like all the other entries (which were one of many in their folders), named by the name of the former lastpass entry.

**Comment by roddhjav** [comment]
This issue should be fixed now.
