### ISSUE TITLE
apple-keychain guide link is dead

### ISSUE THREAD

**Issue by nopdotcom** [roddhjav/pass-import#92]
In the main README table, importing apple-keychain points to https://gist.github.com/sangonz/601f4fd2f039d6ceb2198e2f9f4f01e0 , which is a dead link.

**Comment by roddhjav** [comment]
Thank for this dead link.

The same page now lives into https://gist.github.com/santigz/601f4fd2f039d6ceb2198e2f9f4f01e0. I am going to update the link.
