### ISSUE TITLE
Ubuntu 19.10 (eoan) package: apt-get install pass-import

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#96]
As it is possible to install `pass` via `apt-get` it would be cool to install `pass-import` as an ubuntu package, too.

There are alot of other `pass`-tools already available as ubuntu packages:
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=pass&searchon=names

After that we could ask `pass` package vendor to add `pass-import` as a recommended package of `pass` package.

`pass-import` package should itself recommend its own optional dependencies:
https://github.com/roddhjav/pass-import/blob/master/README.md#installation
Optional dependencies should be also made available as ubuntu packages.

You may provide these packages via a custom PPA repo.

I discourage use of different package manager across the `pass ecosystem`, sure you have no or only little influence on foreign non-pass package vendors, but at least all `pass`-tools should use the same package managers as `pass` itself (not introducing additional package managers like pip3). Ubuntu and tar should be the minimal supported package types. Pip3-based installation should be deprecated.

As long as this is not implemented, ..one question:
How to install https://github.com/libkeepass/pykeepass then i installed `pass import` using the tar method?

**Comment by roddhjav** [comment]
As I am not a debian (or ubuntu) dev I cannot put provide the packages myself so there is little I can do here. I could however provide a .deb package in the future, but as I do not use debian/ubuntu myself that would be a bit of work. PR are welcome ;)
