### ISSUE TITLE
Error message is pointing to a non existing package

### ISSUE THREAD

**Issue by christian-weiss** [roddhjav/pass-import#97]
When i run:
```
pass import --convert --all keepass zusammengefasst.xml
```
i get the following error:
```
 [x] Error: Importing keepass, missing required dependency: pykeepass
You can install it with:
  'sudo apt-get install python3-pykeepass', or
  'pip3 install pykeepass'
```

The command `sudo apt-get install python3-pykeepass` seams to be wrong, as there is no package available with that name :
https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=python3-pykeepass&searchon=names

**Comment by roddhjav** [comment]
There are two things here:

1. As you are importing an xml file, you need to use the xml importer for keepass as seen in the [table in the readme](https://github.com/roddhjav/pass-import#description).
So it should be: `pass import keepass-xml zusammengefasst.xml`

2. Concerning, `sudo apt-get install python3-pykeepass` My mistake, there is no apt package for pykeepass, you need to install it with pip. But, for xml file you do not need it.

**Comment by christian-weiss** [comment]
You are right. I re-build my command line statement based on:
https://github.com/roddhjav/pass-import/issues/57
With `keepass-xml` it is working out of the box - at least it is not printing an error message.

After pushing my password-store to my git server and doing a `git clone` on my Windows 10 PC that there are still 2 issues. We need to reopen:
https://github.com/roddhjav/pass-import/issues/64
https://github.com/roddhjav/pass-import/issues/65

BTW: great work, all other issues from 2018 are gone.

The error message needs to be altered. For that reason i leave this issue open.
